pub const DD_APM_SKILL: &str = include_str!("../skills/dd-apm/SKILL.md");

pub static DD_APM_SUB_SKILLS: &[(&str, &str)] = &[
    (
        "service-remapping/SKILL.md",
        include_str!("../skills/dd-apm/service-remapping/SKILL.md"),
    ),
    (
        "k8s-ssi/agent-install/SKILL.md",
        include_str!("../skills/dd-apm/k8s-ssi/agent-install/SKILL.md"),
    ),
    (
        "k8s-ssi/enable-ssi/SKILL.md",
        include_str!("../skills/dd-apm/k8s-ssi/enable-ssi/SKILL.md"),
    ),
    (
        "k8s-ssi/verify-ssi/SKILL.md",
        include_str!("../skills/dd-apm/k8s-ssi/verify-ssi/SKILL.md"),
    ),
    (
        "k8s-ssi/troubleshoot-ssi/SKILL.md",
        include_str!("../skills/dd-apm/k8s-ssi/troubleshoot-ssi/SKILL.md"),
    ),
    (
        "k8s-ssi/onboarding-summary/SKILL.md",
        include_str!("../skills/dd-apm/k8s-ssi/onboarding-summary/SKILL.md"),
    ),
    (
        "linux-ssi/agent-install/SKILL.md",
        include_str!("../skills/dd-apm/linux-ssi/agent-install/SKILL.md"),
    ),
    (
        "linux-ssi/enable-ssi/SKILL.md",
        include_str!("../skills/dd-apm/linux-ssi/enable-ssi/SKILL.md"),
    ),
    (
        "linux-ssi/verify-ssi/SKILL.md",
        include_str!("../skills/dd-apm/linux-ssi/verify-ssi/SKILL.md"),
    ),
    (
        "linux-ssi/troubleshoot-ssi/SKILL.md",
        include_str!("../skills/dd-apm/linux-ssi/troubleshoot-ssi/SKILL.md"),
    ),
    (
        "linux-ssi/onboarding-summary/SKILL.md",
        include_str!("../skills/dd-apm/linux-ssi/onboarding-summary/SKILL.md"),
    ),
];
